### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by tschmutz** [tschmutz/SplitQuick#2]
- [x] Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
 - [x] Demo User Added
 - [x] Styling
 - [x] Smooth, bug free navigation
   - [x]  Login errors clears when switching from login form to sign up form (and vice-versa)
 - [x]  Adequate and appropriate seeds

**Comment by xnanodax** [comment]
Hey Taylor :) Great progress! Here is some observations I've seen. When you can check these off, we can then close the issue!

## General 
- [ ] Accessing a random route like `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`

## Login 
- [ ] Add username and email labels on the session form

## Sign Up
- [ ] When signing up with a shorter password, the error isn't as helpful. Error: Invalid username or password. 

## When Logged In
- [ ] When clicking on the logo, I am on the `/#/` page and its blank. Did you mean `/#/dashboard` ?
