### ISSUE TITLE
Friending

### ISSUE THREAD

**Issue by tschmutz** [tschmutz/SplitQuick#3]
- [x] Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x] Presentational Components
 - [x]  Styling
 - [x]  Smooth, bug-free navigation
 - [x]  Adequate and appropriate seeds

**Comment by xnanodax** [comment]
- [ ] The search results should include a "+" sign on hover and NOT on hover to make it clear to the user that adding a friend is possible through the search.

**Not Hovering Search Result**
![screen shot 2018-02-06 at 11 08 11 am](https://user-images.githubusercontent.com/20424731/35878752-1249b544-0b2e-11e8-8ca9-a81d466e5695.png)

**Hovering over Search Result**
![screen shot 2018-02-06 at 11 08 16 am](https://user-images.githubusercontent.com/20424731/35878753-1370da42-0b2e-11e8-9f3c-176ca0ada94e.png)

**Comment by xnanodax** [comment]
- [ ] Even though I am friends with Jeff, he shows up on my search result!
![screen shot 2018-02-07 at 9 18 29 am](https://user-images.githubusercontent.com/20424731/35930847-e0095098-0be7-11e8-8909-5445ba629eeb.png)
